const animate = require("tailwindcss-animate")

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  safelist: ["dark"],
  prefix: "",
  
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        sage: "#B5CBB7",
        charcoal: "#2E2E2E",
        softbeige: "#F3EFE6",
        jetblack: "#1A1A1A",
        platinum: "#E5E5E5",
        coldgrey: "#B0B0B0",
        deepblue: "#0B1220",
        liftblue: "#111827",
        highblue: "#1F293B",
        subtleblue: "#1E293B",
        softblue: "#273449",
        textprimary: "#E5E7EB",
        textsecondary: "#9CA3AF",
        textmuted: "#6B7280",
        textdisabled: "#4B5563",
        btnprimary: "#3B82F6",
        btnprimaryfocusring: "#60A5FA",
        btnprimaryhover: "#2563EB",
        btnprimaryactive: "#1D4ED8",
        btnsecondary: "transparent",
        btnsecondaryborder: "##334155",
        btnsecondarytext: "#E5E7EB",
        btnsecondaryhoverbg: "#1E293B",
        cardheaderborder: "#273449",
        drawerborder: "#273449",
        info: "#38BDF8",

        mainbg: "#222222",
        drawerbg: "#1C1C1C",
        dialogbg: "#2F2F2F",
        cardbg: "#2A2A2A",
        hover: "#343434",
        borderblackui: "#3C3C3C",
        primarytext: "#E6E6E6",
        secondarytext: "#B3B3B3",
        mutedtext: "#8A8A8A",
        disabledtext: "#666666",
        primarybuttontext: "#FFFFFF",
        primarybutton: "#3B82F6",
        primarybuttonhover: "#2563EB",
        primarybuttonactive: "#1D4ED8",
        primarybuttontext: "#FFFFFF",
        primarybuttondisabled: "#3B82F650",
        secbutton: "#2F2F2F",
        secbuttonhover: "#3A3A3A",
        secbuttonactive: "#444444",
        secbuttonborder: "#3C3C3C",
        secbuttontext: "#E6E6E6",
        successbutton: "#22C55E",
        successbuttonhover: "#16A34A",
        successbuttonactive: "#15803D",
        successbuttontext: "#FFFFFF",
        warnbutton: "#F59E0B",
        warnbuttonhover: "#D97706",
        warnbuttonactive: "#B45309",
        warnbuttontext: "#1A1A1A",
        dangerbutton: "#EF4444",
        dangerbuttonhover: "#DC2626",
        dangerbuttonactive: "#B91C1C",
        dangerbuttontext: "#FFFFFF",
        infobutton: "#0EA5E9" ,
        infobuttonhover: "#0284C7",
        infobuttonactive: "#0369A1",
        infobuttontext: "#FFFFFF",
        inputbg: "#2A2A2A",
        inputborder: "#3C3C3C",
        inputfocusborder: "#3B82F6",
        inputplaceholder: "#8A8A8A",
        inputdisabledbg: "#262626",
        badgesuccess: "#052E16",
        badgesuccesstext: "#22C55E",
        badgewarning: "#3F2D06",
        badgewarningtext: "#F59E0B",
        badgedanger: "#3B0A0A",
        badgedangertext: "#EF4444",
        badgeinfo: "#082F49",
        badgeinfotext: "#0EA5E9",


        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        quintessential: ['"Quintessential"', 'sans-serif'],
        alumni: ['"Alumni Sans Pinstripe"', 'sans-serif'],
        amsterdam: ['"New Amsterdam"', 'sans-serif'],
        amarante: ['"Amarante"', 'sans-serif'],
        homenaje: ['"Homenaje"', 'sans-serif'],
        talina: ['"Talina"', 'sans-serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "collapsible-down": {
          from: { height: 0 },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        "collapsible-up": {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-in-out",
        "collapsible-up": "collapsible-up 0.2s ease-in-out",
      },
    },
  },
  plugins: [animate],
}